### ISSUE TITLE
Open to Open Source?

### ISSUE THREAD

**Issue by bcpeinhardt** [EbTech/rust-algorithms#17]
Hey there!
I'm a mathematics instructor trying to transition into being a software developer looking for a good first PR and I was wondering if you guys were open to open source contributions. By nature of my job algorithms are kinda my jam and although there are several algorithm repositories on Github, this one seems to be the most recently active one.
I mentor both Rust and C on exercism.io but Rust is the programming language I'm excited about and looking to work with so I figure open source will be a good start.

**Comment by EbTech** [comment]
Hello, thanks for your interest! A few people have contributed here before; you can see their Pull Requests. I often end up requesting and/or making a lot of changes because I'm very particular about the style in this repo, but additions that fit the theme are very welcome.

If you like, perhaps you can suggest an algorithm that you'd like to add? Or if you'd rather build off existing work, #16 was never finished, so you might study that data structure along with the changes I requested to it. There are a few unanswered requests under Issues as well, or you might well have your own ideas!

**Comment by bcpeinhardt** [comment]
I'm not exactly a competitive programmer, and although the video I just watched makes sense, I've never implemented a li chao tree before. Maybe I could start with some convenience tools for efficiency, like a simple Casher struct with a closure and a hashmap. I can do a pull request with edit permissions and you can just close it if you don't think it fits the content!

**Comment by EbTech** [comment]
Sure, there are plenty of areas (e.g., geometry) where this repo is currently lacking. A cacher sounds nice!
