### ISSUE TITLE
Online Docs

### ISSUE THREAD

**Issue by Michael-F-Bryan** [EbTech/rust-algorithms#2]
Is there any chance you could get travis to generate html documentation and upload it to GitHub pages after every commit? I usually find the html docs really useful for quickly navigating a project, then you have the "src" link to look at the implementation.

I did something similar for my [gcode-rs] project.

[gcode-rs]: https://github.com/Michael-F-Bryan/gcode-rs

**Comment by NilSet** [comment]
If you publish to crates.io, then docs.rs will build and host docs for each release published.

**Comment by Michael-F-Bryan** [comment]
That's a good point. I hadn't thought of getting docs.rs to handle hosting docs. I guess my interpretation of this crate is that it's meant as more of a guide on implementing common algorithms in Rust than a data structures library. 

Would there be any other benefits of publishing to crates.io?

**Comment by EbTech** [comment]
Since contest submissions typically must be one file, a user-friendly contest crate should include a utility that automatically removes the extern/use statements, and copies all relevant structs, impls and functions into the main source file. Would anyone like to volunteer? How hard would it be to do that?

**Comment by EbTech** [comment]
Uploaded documentation at https://docs.rs/contest-algorithms
