### ISSUE TITLE
Modular convolution results in incorrect result when a negative value is expected.

### ISSUE THREAD

**Issue by RoyDubnium** [EbTech/rust-algorithms#28]
When computing the convolutions of certain vecs (e.g. [1, -1, 1] with itself), the resulting output can be wildly incorrect. The given example results in [1, 998244351, 3, 998244351, 1].
The value that should be -2 shows up as 998244351. This would suggest the number 998244353 is relevant. I notice that this is a constant named COMMON_PRIME, which does get used at some places in the code. It seems that somewhere, negative numbers are wrapping around to position, with this prime as the divisor. Can you advise how to proceed? This is (as far as I am aware) the only library that has the functionality I need.

**Comment by EbTech** [comment]
Sorry for the counterintuitive behaviour; you can fork the [`impl FFT for i64`](https://github.com/EbTech/rust-algorithms/blob/1d345542b51e38d9ebe39bf52c855df8ec2929f8/src/math/fft.rs#L80) to better suit your purposes. The current implementation of integer convolution is done modulo 998244353, so the answers should be "correct" but shifted into the range [0, 998244352]. If you want negative numbers to show up as negative, you may replace the `extract` function with the following:
```
fn extract(f: Self::F) -> Self {
    if f.val > COMMON_PRIME / 2 { f.val - COMMON_PRIME } else { f.val }
}
```
In addition, note that the convolution on `f64` uses a [different implementation](https://github.com/EbTech/rust-algorithms/blob/1d345542b51e38d9ebe39bf52c855df8ec2929f8/src/math/fft.rs#L54), based on floating-point complex numbers instead of modular arithmetic.
